### ISSUE TITLE
Chat problem!

### ISSUE THREAD

**Issue by csaksapi** [Limmek/MStats-for-rust#8] opened 2020-04-14 21:12 UTC
Hey Dude!

I haven't applied in a long time, I know, and I forgot to thank you for your work so far. I apologize for that!

I recently restarted the rust and the plugin you wrote is flawless except for one thing. Due to the global and team chat update, it does not log chat into mysql.

Do you have any idea for this? I just want to log in to global chat. The rest is not important.

Thank you so much for reading through this! :)

I wish you all the best!
ps: and thanks for all the work so far

**Comment by Limmek** [comment] 2020-04-15 12:19
Hey man!

Thank you very much sir!
It's okay dude i'm just glad you still find it useful!

I will take a look on it and update the plugin for you :)

**Comment by csaksapi** [comment] 2020-04-15 14:10
Yo!

THX man! u r the best!

**Comment by Limmek** [comment] 2020-04-15 15:23
Okay it is now updated and should work just fine but it is not fully tested.

Please try it out and report back :)

**Comment by csaksapi** [comment] 2020-04-15 16:00
Working!!! Thx a lot! :D

**Comment by csaksapi** [comment] 2020-04-15 16:07
one moment:

any idea?

![terminal](https://user-images.githubusercontent.com/46930232/79360192-d9b0cb00-7f43-11ea-8b14-77835496909b.png)

**Comment by Limmek** [comment] 2020-04-15 16:15
It should been fixed now :)

Please drop the database. use the commands
mstats.drop
mstats.reload

**Comment by csaksapi** [comment] 2020-04-15 17:07
seems to work nicely :)
Thanks for the extremely fast repair!

RESPECT!

**Comment by Limmek** [comment] 2020-04-15 17:36
Sweet no problem  :)

**Comment by csaksapi** [comment] 2020-04-15 20:42
you must hate me already :)

![kép](https://user-images.githubusercontent.com/46930232/79386353-49d24780-7f6a-11ea-90f1-41488cc9b163.png)

**Comment by Limmek** [comment] 2020-04-15 21:02
haha no i don't. did you run mstats.drop and mstats.reload?

and witch command was called when the error ocurd?

**Comment by csaksapi** [comment] 2020-04-15 21:06
holy... you are righ! that step was missed :D sorry for my stupidity

**Comment by csaksapi** [comment] 2020-04-15 21:09
the story is so much that we are both working on a server, I run the website, my partner makes custom maps (unity, rusteditor)
and there are prefabs when you see one of these two, but probably drop & reload was just the problem

**Comment by Limmek** [comment] 2020-04-15 21:46
ahh i see it sound like a fun project :) 
Yeah it should work just fine after a drop and reload, but i'm not sure as i have not tested it.

The reason why you needed to reload tables is because i did make the player_id unique in the first place but then it would not add new records to the table.. You could edit the database table manually but a drop and reload is easier.

**Comment by Limmek** [comment] 2020-04-17 07:47
Everything working as intended? :)

**Comment by csaksapi** [comment] 2020-04-17 08:07
Perfect! Thx a lot!
:D

**Comment by Limmek** [comment] 2020-04-17 08:08
No problem mate! Have a nice day and good luck with the project. :)

**Closed as completed by Limmek** 2020-04-17 08:08 UTC
Labels: Bug, Fixed
